apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ollama-ia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        env:
        - name: OLLAMA_API_BASE_URL
          value: "http://ollama.ollama-ia.svc.cluster.local:11434"
        - name: WEBUI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: open-webui-secret
              key: web-secret
        volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
      volumes:
      - name: open-webui-data
        persistentVolumeClaim:
          claimName: open-webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: ollama-ia
spec:
  selector:
    app: open-webui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-data
  namespace: ollama-ia
  labels:
    type: local
spec:
  storageClassName: gp3
  capacity:
    storage: 8G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: ollama-ia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: Secret
apiVersion: v1
metadata:
  name: open-webui-secret
  namespace: ollama-ia
stringData:
  web-secret: "bip4NXM5WmFYXjl5bzh5RQ=="
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ollama-ui-gateway
  namespace: ollama-ia
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 80
        protocol: HTTP
    #   tls:
    #     httpsRedirect: true
    # - hosts:
    #     - "*"
    #   port:
    #     name: https-workloads
    #     number: 443
    #     protocol: HTTP
    #   tls:
    #     mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ollama
  namespace: ollama-ia
spec:
  gateways:
    - ollama-ui-gateway
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: open-webui.ollama-ia.svc.cluster.local
            port:
              number: 8080
          weight: 100